// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function GetInputData() {
  return window['go']['main']['App']['GetInputData']();
}

export function GetRemainingSeconds() {
  return window['go']['main']['App']['GetRemainingSeconds']();
}

export function Rollback(arg1, arg2, arg3) {
  return window['go']['main']['App']['Rollback'](arg1, arg2, arg3);
}

export function Submit(arg1, arg2) {
  return window['go']['main']['App']['Submit'](arg1, arg2);
}
