// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Cancel():Promise<void>;

export function GetInputData():Promise<main.InputData>;

export function GetRemainingSeconds():Promise<number>;

export function Rollback(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function Submit(arg1:Array<string>,arg2:string):Promise<void>;
